from selenium import webdriver
import pyautogui 
from time import sleep

navegador = webdriver.Chrome()
navegador.get('https://temp-mail.org/pt/')
sleep(5)
pyautogui.click(x=730, y=337)
pyautogui.hotkey('ctrl', 't')
pyautogui.write('https://www.instagram.com')
pyautogui.hotkey('enter')
sleep(5)
pyautogui.click(x=786, y=621)
sleep(2)
pyautogui.click(x=524, y=424)
pyautogui.hotkey('ctrl', 'v')
sleep(1)
pyautogui.hotkey('ctrl', 't')
sleep(1)
pyautogui.click(x=436, y=70)
pyautogui.write('https://gerador-nomes.herokuapp.com')
pyautogui.hotkey('enter')
sleep(5)
pyautogui.tripleClick(x=475, y=355)
pyautogui.hotkey('ctrl', 'c')
sleep(1)
pyautogui.click(x=285, y=30)
sleep(1)
pyautogui.click(x=495, y=467)
pyautogui.hotkey('ctrl', 'v')
pyautogui.click(x=638, y=509)
sleep(1)
pyautogui.hotkey('ctrl', 't')
sleep(1)
pyautogui.click(x=391, y=70)
pyautogui.write('https://www.geradordesenha.com.br')
pyautogui.hotkey('enter')
sleep(4)
pyautogui.click(x=520, y=687)
pyautogui.doubleClick(x=526, y=604)
pyautogui.hotkey('ctrl', 'c')
pyautogui.click(x=295, y=30)
pyautogui.click(x=459, y=555)
pyautogui.hotkey('ctrl', 'v')
sleep(2)
pyautogui.click(x=520, y=599)
sleep(2)
pyautogui.click(x=488, y=430)
pyautogui.click(x=458, y=460)
pyautogui.click(x=543, y=433)
pyautogui.click(x=533, y=360)
pyautogui.click(x=610, y=435)
pyautogui.click(x=596, y=409)
sleep(1)
pyautogui.click(x=522, y=564)
sleep(2)
pyautogui.click(x=110, y=32)
sleep(1)
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
sleep(20)
pyautogui.hotkey('ctrl', 'shift', 'i')
sleep(5)
pyautogui.click(x=514, y=147)
sleep(3)
pyautogui.moveTo(x=111, y=555)
pyautogui.hotkey('ctrl', 'shift', 'c')
sleep(3)
pyautogui.doubleClick(x=843, y=293)
sleep(3)
pyautogui.hotkey('ctrl', 'c')
pyautogui.click(x=116, y=33)
sleep(3)
pyautogui.click(x=300, y=32)
pyautogui.click(x=512, y=427)
pyautogui.hotkey('ctrl', 'v')
sleep(3)
pyautogui.hotkey('backspace')
pyautogui.hotkey('backspace')
pyautogui.click(x=522, y=474)
sleep(15)

#seguir lwxzzz
pyautogui.hotkey('ctrl', 't')
pyautogui.write('https://www.instagram.com/lwxzzz/')
pyautogui.hotkey('enter')
sleep(7)
pyautogui.click(x=516, y=229)
sleep(1)

navegador.quit()

navegador = webdriver.Chrome()
navegador.get('https://temp-mail.org/pt/')
sleep(5)
pyautogui.click(x=730, y=337)
pyautogui.hotkey('ctrl', 't')
pyautogui.write('https://www.instagram.com')
pyautogui.hotkey('enter')
sleep(5)
pyautogui.click(x=786, y=621)
sleep(2)
pyautogui.click(x=524, y=424)
pyautogui.hotkey('ctrl', 'v')
sleep(1)
pyautogui.hotkey('ctrl', 't')
sleep(1)
pyautogui.click(x=436, y=70)
pyautogui.write('https://gerador-nomes.herokuapp.com')
pyautogui.hotkey('enter')
sleep(5)
pyautogui.tripleClick(x=475, y=355)
pyautogui.hotkey('ctrl', 'c')
sleep(1)
pyautogui.click(x=285, y=30)
sleep(1)
pyautogui.click(x=495, y=467)
pyautogui.hotkey('ctrl', 'v')
pyautogui.click(x=638, y=509)
sleep(1)
pyautogui.hotkey('ctrl', 't')
sleep(1)
pyautogui.click(x=391, y=70)
pyautogui.write('https://www.geradordesenha.com.br')
pyautogui.hotkey('enter')
sleep(4)
pyautogui.click(x=520, y=687)
pyautogui.doubleClick(x=526, y=604)
pyautogui.hotkey('ctrl', 'c')
pyautogui.click(x=295, y=30)
pyautogui.click(x=459, y=555)
pyautogui.hotkey('ctrl', 'v')
sleep(2)
pyautogui.click(x=520, y=599)
sleep(2)
pyautogui.click(x=488, y=430)
pyautogui.click(x=458, y=460)
pyautogui.click(x=543, y=433)
pyautogui.click(x=533, y=360)
pyautogui.click(x=610, y=435)
pyautogui.click(x=596, y=409)
sleep(1)
pyautogui.click(x=522, y=564)
sleep(2)
pyautogui.click(x=110, y=32)
sleep(1)
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
sleep(20)
pyautogui.hotkey('ctrl', 'shift', 'i')
sleep(5)
pyautogui.click(x=514, y=147)
sleep(3)
pyautogui.moveTo(x=111, y=555)
pyautogui.hotkey('ctrl', 'shift', 'c')
sleep(3)
pyautogui.doubleClick(x=843, y=293)
sleep(3)
pyautogui.hotkey('ctrl', 'c')
pyautogui.click(x=116, y=33)
sleep(3)
pyautogui.click(x=300, y=32)
pyautogui.click(x=512, y=427)
pyautogui.hotkey('ctrl', 'v')
sleep(3)
pyautogui.hotkey('backspace')
pyautogui.hotkey('backspace')
pyautogui.click(x=522, y=474)
sleep(15)

#seguir lwxzzz
pyautogui.hotkey('ctrl', 't')
pyautogui.write('https://www.instagram.com/lwxzzz/')
pyautogui.hotkey('enter')
sleep(7)
pyautogui.click(x=516, y=229)
sleep(1)

navegador.quit()

navegador = webdriver.Chrome()
navegador.get('https://temp-mail.org/pt/')
sleep(5)
pyautogui.click(x=730, y=337)
pyautogui.hotkey('ctrl', 't')
pyautogui.write('https://www.instagram.com')
pyautogui.hotkey('enter')
sleep(5)
pyautogui.click(x=786, y=621)
sleep(2)
pyautogui.click(x=524, y=424)
pyautogui.hotkey('ctrl', 'v')
sleep(1)
pyautogui.hotkey('ctrl', 't')
sleep(1)
pyautogui.click(x=436, y=70)
pyautogui.write('https://gerador-nomes.herokuapp.com')
pyautogui.hotkey('enter')
sleep(5)
pyautogui.tripleClick(x=475, y=355)
pyautogui.hotkey('ctrl', 'c')
sleep(1)
pyautogui.click(x=285, y=30)
sleep(1)
pyautogui.click(x=495, y=467)
pyautogui.hotkey('ctrl', 'v')
pyautogui.click(x=638, y=509)
sleep(1)
pyautogui.hotkey('ctrl', 't')
sleep(1)
pyautogui.click(x=391, y=70)
pyautogui.write('https://www.geradordesenha.com.br')
pyautogui.hotkey('enter')
sleep(4)
pyautogui.click(x=520, y=687)
pyautogui.doubleClick(x=526, y=604)
pyautogui.hotkey('ctrl', 'c')
pyautogui.click(x=295, y=30)
pyautogui.click(x=459, y=555)
pyautogui.hotkey('ctrl', 'v')
sleep(2)
pyautogui.click(x=520, y=599)
sleep(2)
pyautogui.click(x=488, y=430)
pyautogui.click(x=458, y=460)
pyautogui.click(x=543, y=433)
pyautogui.click(x=533, y=360)
pyautogui.click(x=610, y=435)
pyautogui.click(x=596, y=409)
sleep(1)
pyautogui.click(x=522, y=564)
sleep(2)
pyautogui.click(x=110, y=32)
sleep(1)
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
sleep(20)
pyautogui.hotkey('ctrl', 'shift', 'i')
sleep(5)
pyautogui.click(x=514, y=147)
sleep(3)
pyautogui.moveTo(x=111, y=555)
pyautogui.hotkey('ctrl', 'shift', 'c')
sleep(3)
pyautogui.doubleClick(x=843, y=293)
sleep(3)
pyautogui.hotkey('ctrl', 'c')
pyautogui.click(x=116, y=33)
sleep(3)
pyautogui.click(x=300, y=32)
pyautogui.click(x=512, y=427)
pyautogui.hotkey('ctrl', 'v')
sleep(3)
pyautogui.hotkey('backspace')
pyautogui.hotkey('backspace')
pyautogui.click(x=522, y=474)
sleep(15)

#seguir lwxzzz
pyautogui.hotkey('ctrl', 't')
pyautogui.write('https://www.instagram.com/lwxzzz/')
pyautogui.hotkey('enter')
sleep(7)
pyautogui.click(x=516, y=229)
sleep(1)

navegador.quit()

navegador = webdriver.Chrome()
navegador.get('https://temp-mail.org/pt/')
sleep(5)
pyautogui.click(x=730, y=337)
pyautogui.hotkey('ctrl', 't')
pyautogui.write('https://www.instagram.com')
pyautogui.hotkey('enter')
sleep(5)
pyautogui.click(x=786, y=621)
sleep(2)
pyautogui.click(x=524, y=424)
pyautogui.hotkey('ctrl', 'v')
sleep(1)
pyautogui.hotkey('ctrl', 't')
sleep(1)
pyautogui.click(x=436, y=70)
pyautogui.write('https://gerador-nomes.herokuapp.com')
pyautogui.hotkey('enter')
sleep(5)
pyautogui.tripleClick(x=475, y=355)
pyautogui.hotkey('ctrl', 'c')
sleep(1)
pyautogui.click(x=285, y=30)
sleep(1)
pyautogui.click(x=495, y=467)
pyautogui.hotkey('ctrl', 'v')
pyautogui.click(x=638, y=509)
sleep(1)
pyautogui.hotkey('ctrl', 't')
sleep(1)
pyautogui.click(x=391, y=70)
pyautogui.write('https://www.geradordesenha.com.br')
pyautogui.hotkey('enter')
sleep(4)
pyautogui.click(x=520, y=687)
pyautogui.doubleClick(x=526, y=604)
pyautogui.hotkey('ctrl', 'c')
pyautogui.click(x=295, y=30)
pyautogui.click(x=459, y=555)
pyautogui.hotkey('ctrl', 'v')
sleep(2)
pyautogui.click(x=520, y=599)
sleep(2)
pyautogui.click(x=488, y=430)
pyautogui.click(x=458, y=460)
pyautogui.click(x=543, y=433)
pyautogui.click(x=533, y=360)
pyautogui.click(x=610, y=435)
pyautogui.click(x=596, y=409)
sleep(1)
pyautogui.click(x=522, y=564)
sleep(2)
pyautogui.click(x=110, y=32)
sleep(1)
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
sleep(20)
pyautogui.hotkey('ctrl', 'shift', 'i')
sleep(5)
pyautogui.click(x=514, y=147)
sleep(3)
pyautogui.moveTo(x=111, y=555)
pyautogui.hotkey('ctrl', 'shift', 'c')
sleep(3)
pyautogui.doubleClick(x=843, y=293)
sleep(3)
pyautogui.hotkey('ctrl', 'c')
pyautogui.click(x=116, y=33)
sleep(3)
pyautogui.click(x=300, y=32)
pyautogui.click(x=512, y=427)
pyautogui.hotkey('ctrl', 'v')
sleep(3)
pyautogui.hotkey('backspace')
pyautogui.hotkey('backspace')
pyautogui.click(x=522, y=474)
sleep(15)

#seguir lwxzzz
pyautogui.hotkey('ctrl', 't')
pyautogui.write('https://www.instagram.com/lwxzzz/')
pyautogui.hotkey('enter')
sleep(7)
pyautogui.click(x=516, y=229)
sleep(1)

navegador.quit()

navegador = webdriver.Chrome()
navegador.get('https://temp-mail.org/pt/')
sleep(5)
pyautogui.click(x=730, y=337)
pyautogui.hotkey('ctrl', 't')
pyautogui.write('https://www.instagram.com')
pyautogui.hotkey('enter')
sleep(5)
pyautogui.click(x=786, y=621)
sleep(2)
pyautogui.click(x=524, y=424)
pyautogui.hotkey('ctrl', 'v')
sleep(1)
pyautogui.hotkey('ctrl', 't')
sleep(1)
pyautogui.click(x=436, y=70)
pyautogui.write('https://gerador-nomes.herokuapp.com')
pyautogui.hotkey('enter')
sleep(5)
pyautogui.tripleClick(x=475, y=355)
pyautogui.hotkey('ctrl', 'c')
sleep(1)
pyautogui.click(x=285, y=30)
sleep(1)
pyautogui.click(x=495, y=467)
pyautogui.hotkey('ctrl', 'v')
pyautogui.click(x=638, y=509)
sleep(1)
pyautogui.hotkey('ctrl', 't')
sleep(1)
pyautogui.click(x=391, y=70)
pyautogui.write('https://www.geradordesenha.com.br')
pyautogui.hotkey('enter')
sleep(4)
pyautogui.click(x=520, y=687)
pyautogui.doubleClick(x=526, y=604)
pyautogui.hotkey('ctrl', 'c')
pyautogui.click(x=295, y=30)
pyautogui.click(x=459, y=555)
pyautogui.hotkey('ctrl', 'v')
sleep(2)
pyautogui.click(x=520, y=599)
sleep(2)
pyautogui.click(x=488, y=430)
pyautogui.click(x=458, y=460)
pyautogui.click(x=543, y=433)
pyautogui.click(x=533, y=360)
pyautogui.click(x=610, y=435)
pyautogui.click(x=596, y=409)
sleep(1)
pyautogui.click(x=522, y=564)
sleep(2)
pyautogui.click(x=110, y=32)
sleep(1)
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
sleep(20)
pyautogui.hotkey('ctrl', 'shift', 'i')
sleep(5)
pyautogui.click(x=514, y=147)
sleep(3)
pyautogui.moveTo(x=111, y=555)
pyautogui.hotkey('ctrl', 'shift', 'c')
sleep(3)
pyautogui.doubleClick(x=843, y=293)
sleep(3)
pyautogui.hotkey('ctrl', 'c')
pyautogui.click(x=116, y=33)
sleep(3)
pyautogui.click(x=300, y=32)
pyautogui.click(x=512, y=427)
pyautogui.hotkey('ctrl', 'v')
sleep(3)
pyautogui.hotkey('backspace')
pyautogui.hotkey('backspace')
pyautogui.click(x=522, y=474)
sleep(15)

#seguir lwxzzz
pyautogui.hotkey('ctrl', 't')
pyautogui.write('https://www.instagram.com/lwxzzz/')
pyautogui.hotkey('enter')
sleep(7)
pyautogui.click(x=516, y=229)
sleep(1)

navegador.quit()

navegador = webdriver.Chrome()
navegador.get('https://temp-mail.org/pt/')
sleep(5)
pyautogui.click(x=730, y=337)
pyautogui.hotkey('ctrl', 't')
pyautogui.write('https://www.instagram.com')
pyautogui.hotkey('enter')
sleep(5)
pyautogui.click(x=786, y=621)
sleep(2)
pyautogui.click(x=524, y=424)
pyautogui.hotkey('ctrl', 'v')
sleep(1)
pyautogui.hotkey('ctrl', 't')
sleep(1)
pyautogui.click(x=436, y=70)
pyautogui.write('https://gerador-nomes.herokuapp.com')
pyautogui.hotkey('enter')
sleep(5)
pyautogui.tripleClick(x=475, y=355)
pyautogui.hotkey('ctrl', 'c')
sleep(1)
pyautogui.click(x=285, y=30)
sleep(1)
pyautogui.click(x=495, y=467)
pyautogui.hotkey('ctrl', 'v')
pyautogui.click(x=638, y=509)
sleep(1)
pyautogui.hotkey('ctrl', 't')
sleep(1)
pyautogui.click(x=391, y=70)
pyautogui.write('https://www.geradordesenha.com.br')
pyautogui.hotkey('enter')
sleep(4)
pyautogui.click(x=520, y=687)
pyautogui.doubleClick(x=526, y=604)
pyautogui.hotkey('ctrl', 'c')
pyautogui.click(x=295, y=30)
pyautogui.click(x=459, y=555)
pyautogui.hotkey('ctrl', 'v')
sleep(2)
pyautogui.click(x=520, y=599)
sleep(2)
pyautogui.click(x=488, y=430)
pyautogui.click(x=458, y=460)
pyautogui.click(x=543, y=433)
pyautogui.click(x=533, y=360)
pyautogui.click(x=610, y=435)
pyautogui.click(x=596, y=409)
sleep(1)
pyautogui.click(x=522, y=564)
sleep(2)
pyautogui.click(x=110, y=32)
sleep(1)
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
sleep(20)
pyautogui.hotkey('ctrl', 'shift', 'i')
sleep(5)
pyautogui.click(x=514, y=147)
sleep(3)
pyautogui.moveTo(x=111, y=555)
pyautogui.hotkey('ctrl', 'shift', 'c')
sleep(3)
pyautogui.doubleClick(x=843, y=293)
sleep(3)
pyautogui.hotkey('ctrl', 'c')
pyautogui.click(x=116, y=33)
sleep(3)
pyautogui.click(x=300, y=32)
pyautogui.click(x=512, y=427)
pyautogui.hotkey('ctrl', 'v')
sleep(3)
pyautogui.hotkey('backspace')
pyautogui.hotkey('backspace')
pyautogui.click(x=522, y=474)
sleep(15)

#seguir lwxzzz
pyautogui.hotkey('ctrl', 't')
pyautogui.write('https://www.instagram.com/lwxzzz/')
pyautogui.hotkey('enter')
sleep(7)
pyautogui.click(x=516, y=229)
sleep(1)

navegador.quit()

navegador = webdriver.Chrome()
navegador.get('https://temp-mail.org/pt/')
sleep(5)
pyautogui.click(x=730, y=337)
pyautogui.hotkey('ctrl', 't')
pyautogui.write('https://www.instagram.com')
pyautogui.hotkey('enter')
sleep(5)
pyautogui.click(x=786, y=621)
sleep(2)
pyautogui.click(x=524, y=424)
pyautogui.hotkey('ctrl', 'v')
sleep(1)
pyautogui.hotkey('ctrl', 't')
sleep(1)
pyautogui.click(x=436, y=70)
pyautogui.write('https://gerador-nomes.herokuapp.com')
pyautogui.hotkey('enter')
sleep(5)
pyautogui.tripleClick(x=475, y=355)
pyautogui.hotkey('ctrl', 'c')
sleep(1)
pyautogui.click(x=285, y=30)
sleep(1)
pyautogui.click(x=495, y=467)
pyautogui.hotkey('ctrl', 'v')
pyautogui.click(x=638, y=509)
sleep(1)
pyautogui.hotkey('ctrl', 't')
sleep(1)
pyautogui.click(x=391, y=70)
pyautogui.write('https://www.geradordesenha.com.br')
pyautogui.hotkey('enter')
sleep(4)
pyautogui.click(x=520, y=687)
pyautogui.doubleClick(x=526, y=604)
pyautogui.hotkey('ctrl', 'c')
pyautogui.click(x=295, y=30)
pyautogui.click(x=459, y=555)
pyautogui.hotkey('ctrl', 'v')
sleep(2)
pyautogui.click(x=520, y=599)
sleep(2)
pyautogui.click(x=488, y=430)
pyautogui.click(x=458, y=460)
pyautogui.click(x=543, y=433)
pyautogui.click(x=533, y=360)
pyautogui.click(x=610, y=435)
pyautogui.click(x=596, y=409)
sleep(1)
pyautogui.click(x=522, y=564)
sleep(2)
pyautogui.click(x=110, y=32)
sleep(1)
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
sleep(20)
pyautogui.hotkey('ctrl', 'shift', 'i')
sleep(5)
pyautogui.click(x=514, y=147)
sleep(3)
pyautogui.moveTo(x=111, y=555)
pyautogui.hotkey('ctrl', 'shift', 'c')
sleep(3)
pyautogui.doubleClick(x=843, y=293)
sleep(3)
pyautogui.hotkey('ctrl', 'c')
pyautogui.click(x=116, y=33)
sleep(3)
pyautogui.click(x=300, y=32)
pyautogui.click(x=512, y=427)
pyautogui.hotkey('ctrl', 'v')
sleep(3)
pyautogui.hotkey('backspace')
pyautogui.hotkey('backspace')
pyautogui.click(x=522, y=474)
sleep(15)

#seguir lwxzzz
pyautogui.hotkey('ctrl', 't')
pyautogui.write('https://www.instagram.com/lwxzzz/')
pyautogui.hotkey('enter')
sleep(7)
pyautogui.click(x=516, y=229)
sleep(1)

navegador.quit()

navegador = webdriver.Chrome()
navegador.get('https://temp-mail.org/pt/')
sleep(5)
pyautogui.click(x=730, y=337)
pyautogui.hotkey('ctrl', 't')
pyautogui.write('https://www.instagram.com')
pyautogui.hotkey('enter')
sleep(5)
pyautogui.click(x=786, y=621)
sleep(2)
pyautogui.click(x=524, y=424)
pyautogui.hotkey('ctrl', 'v')
sleep(1)
pyautogui.hotkey('ctrl', 't')
sleep(1)
pyautogui.click(x=436, y=70)
pyautogui.write('https://gerador-nomes.herokuapp.com')
pyautogui.hotkey('enter')
sleep(5)
pyautogui.tripleClick(x=475, y=355)
pyautogui.hotkey('ctrl', 'c')
sleep(1)
pyautogui.click(x=285, y=30)
sleep(1)
pyautogui.click(x=495, y=467)
pyautogui.hotkey('ctrl', 'v')
pyautogui.click(x=638, y=509)
sleep(1)
pyautogui.hotkey('ctrl', 't')
sleep(1)
pyautogui.click(x=391, y=70)
pyautogui.write('https://www.geradordesenha.com.br')
pyautogui.hotkey('enter')
sleep(4)
pyautogui.click(x=520, y=687)
pyautogui.doubleClick(x=526, y=604)
pyautogui.hotkey('ctrl', 'c')
pyautogui.click(x=295, y=30)
pyautogui.click(x=459, y=555)
pyautogui.hotkey('ctrl', 'v')
sleep(2)
pyautogui.click(x=520, y=599)
sleep(2)
pyautogui.click(x=488, y=430)
pyautogui.click(x=458, y=460)
pyautogui.click(x=543, y=433)
pyautogui.click(x=533, y=360)
pyautogui.click(x=610, y=435)
pyautogui.click(x=596, y=409)
sleep(1)
pyautogui.click(x=522, y=564)
sleep(2)
pyautogui.click(x=110, y=32)
sleep(1)
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
sleep(20)
pyautogui.hotkey('ctrl', 'shift', 'i')
sleep(5)
pyautogui.click(x=514, y=147)
sleep(3)
pyautogui.moveTo(x=111, y=555)
pyautogui.hotkey('ctrl', 'shift', 'c')
sleep(3)
pyautogui.doubleClick(x=843, y=293)
sleep(3)
pyautogui.hotkey('ctrl', 'c')
pyautogui.click(x=116, y=33)
sleep(3)
pyautogui.click(x=300, y=32)
pyautogui.click(x=512, y=427)
pyautogui.hotkey('ctrl', 'v')
sleep(3)
pyautogui.hotkey('backspace')
pyautogui.hotkey('backspace')
pyautogui.click(x=522, y=474)
sleep(15)

#seguir lwxzzz
pyautogui.hotkey('ctrl', 't')
pyautogui.write('https://www.instagram.com/lwxzzz/')
pyautogui.hotkey('enter')
sleep(7)
pyautogui.click(x=516, y=229)
sleep(1)

navegador.quit()

navegador = webdriver.Chrome()
navegador.get('https://temp-mail.org/pt/')
sleep(5)
pyautogui.click(x=730, y=337)
pyautogui.hotkey('ctrl', 't')
pyautogui.write('https://www.instagram.com')
pyautogui.hotkey('enter')
sleep(5)
pyautogui.click(x=786, y=621)
sleep(2)
pyautogui.click(x=524, y=424)
pyautogui.hotkey('ctrl', 'v')
sleep(1)
pyautogui.hotkey('ctrl', 't')
sleep(1)
pyautogui.click(x=436, y=70)
pyautogui.write('https://gerador-nomes.herokuapp.com')
pyautogui.hotkey('enter')
sleep(5)
pyautogui.tripleClick(x=475, y=355)
pyautogui.hotkey('ctrl', 'c')
sleep(1)
pyautogui.click(x=285, y=30)
sleep(1)
pyautogui.click(x=495, y=467)
pyautogui.hotkey('ctrl', 'v')
pyautogui.click(x=638, y=509)
sleep(1)
pyautogui.hotkey('ctrl', 't')
sleep(1)
pyautogui.click(x=391, y=70)
pyautogui.write('https://www.geradordesenha.com.br')
pyautogui.hotkey('enter')
sleep(4)
pyautogui.click(x=520, y=687)
pyautogui.doubleClick(x=526, y=604)
pyautogui.hotkey('ctrl', 'c')
pyautogui.click(x=295, y=30)
pyautogui.click(x=459, y=555)
pyautogui.hotkey('ctrl', 'v')
sleep(2)
pyautogui.click(x=520, y=599)
sleep(2)
pyautogui.click(x=488, y=430)
pyautogui.click(x=458, y=460)
pyautogui.click(x=543, y=433)
pyautogui.click(x=533, y=360)
pyautogui.click(x=610, y=435)
pyautogui.click(x=596, y=409)
sleep(1)
pyautogui.click(x=522, y=564)
sleep(2)
pyautogui.click(x=110, y=32)
sleep(1)
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
sleep(20)
pyautogui.hotkey('ctrl', 'shift', 'i')
sleep(5)
pyautogui.click(x=514, y=147)
sleep(3)
pyautogui.moveTo(x=111, y=555)
pyautogui.hotkey('ctrl', 'shift', 'c')
sleep(3)
pyautogui.doubleClick(x=843, y=293)
sleep(3)
pyautogui.hotkey('ctrl', 'c')
pyautogui.click(x=116, y=33)
sleep(3)
pyautogui.click(x=300, y=32)
pyautogui.click(x=512, y=427)
pyautogui.hotkey('ctrl', 'v')
sleep(3)
pyautogui.hotkey('backspace')
pyautogui.hotkey('backspace')
pyautogui.click(x=522, y=474)
sleep(15)

#seguir lwxzzz
pyautogui.hotkey('ctrl', 't')
pyautogui.write('https://www.instagram.com/lwxzzz/')
pyautogui.hotkey('enter')
sleep(7)
pyautogui.click(x=516, y=229)
sleep(1)

navegador.quit()

navegador = webdriver.Chrome()
navegador.get('https://temp-mail.org/pt/')
sleep(5)
pyautogui.click(x=730, y=337)
pyautogui.hotkey('ctrl', 't')
pyautogui.write('https://www.instagram.com')
pyautogui.hotkey('enter')
sleep(5)
pyautogui.click(x=786, y=621)
sleep(2)
pyautogui.click(x=524, y=424)
pyautogui.hotkey('ctrl', 'v')
sleep(1)
pyautogui.hotkey('ctrl', 't')
sleep(1)
pyautogui.click(x=436, y=70)
pyautogui.write('https://gerador-nomes.herokuapp.com')
pyautogui.hotkey('enter')
sleep(5)
pyautogui.tripleClick(x=475, y=355)
pyautogui.hotkey('ctrl', 'c')
sleep(1)
pyautogui.click(x=285, y=30)
sleep(1)
pyautogui.click(x=495, y=467)
pyautogui.hotkey('ctrl', 'v')
pyautogui.click(x=638, y=509)
sleep(1)
pyautogui.hotkey('ctrl', 't')
sleep(1)
pyautogui.click(x=391, y=70)
pyautogui.write('https://www.geradordesenha.com.br')
pyautogui.hotkey('enter')
sleep(4)
pyautogui.click(x=520, y=687)
pyautogui.doubleClick(x=526, y=604)
pyautogui.hotkey('ctrl', 'c')
pyautogui.click(x=295, y=30)
pyautogui.click(x=459, y=555)
pyautogui.hotkey('ctrl', 'v')
sleep(2)
pyautogui.click(x=520, y=599)
sleep(2)
pyautogui.click(x=488, y=430)
pyautogui.click(x=458, y=460)
pyautogui.click(x=543, y=433)
pyautogui.click(x=533, y=360)
pyautogui.click(x=610, y=435)
pyautogui.click(x=596, y=409)
sleep(1)
pyautogui.click(x=522, y=564)
sleep(2)
pyautogui.click(x=110, y=32)
sleep(1)
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
sleep(20)
pyautogui.hotkey('ctrl', 'shift', 'i')
sleep(5)
pyautogui.click(x=514, y=147)
sleep(3)
pyautogui.moveTo(x=111, y=555)
pyautogui.hotkey('ctrl', 'shift', 'c')
sleep(3)
pyautogui.doubleClick(x=843, y=293)
sleep(3)
pyautogui.hotkey('ctrl', 'c')
pyautogui.click(x=116, y=33)
sleep(3)
pyautogui.click(x=300, y=32)
pyautogui.click(x=512, y=427)
pyautogui.hotkey('ctrl', 'v')
sleep(3)
pyautogui.hotkey('backspace')
pyautogui.hotkey('backspace')
pyautogui.click(x=522, y=474)
sleep(15)

#seguir lwxzzz
pyautogui.hotkey('ctrl', 't')
pyautogui.write('https://www.instagram.com/lwxzzz/')
pyautogui.hotkey('enter')
sleep(7)
pyautogui.click(x=516, y=229)
sleep(1)

navegador.quit()











